name: register_appilcation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0-321.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.1
  bloc: ^8.1.4
  bloc_provider: ^1.0.0
  get_it: ^8.0.0
  go_router: ^14.3.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  retrofit_generator: ^9.1.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
